<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Zhong">
<meta name="dcterms.date" content="2026-04-15">
<meta name="description" content="Walking through the core machinery of classical frequentist">

<title>A/B Testing a Call to Action – Alex Zhong</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Alex Zhong</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-ab-test-as-a-statistical-problem" id="toc-the-ab-test-as-a-statistical-problem" class="nav-link" data-scroll-target="#the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data">Simulating Data</a></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers">The Law of Large Numbers</a></li>
  <li><a href="#bootstrap-standard-errors" id="toc-bootstrap-standard-errors" class="nav-link" data-scroll-target="#bootstrap-standard-errors">Bootstrap Standard Errors</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#the-t-test-as-a-regression" id="toc-the-t-test-as-a-regression" class="nav-link" data-scroll-target="#the-t-test-as-a-regression">The T-Test as a Regression</a></li>
  <li><a href="#the-problem-with-peeking" id="toc-the-problem-with-peeking" class="nav-link" data-scroll-target="#the-problem-with-peeking">The Problem with Peeking</a></li>
  <li><a href="#closing-remarks" id="toc-closing-remarks" class="nav-link" data-scroll-target="#closing-remarks">Closing Remarks</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">A/B Testing a Call to Action</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Simulating Key Ideas from Classical Frequentist Statistics</p>
  <div class="quarto-categories">
    <div class="quarto-category">statistics</div>
    <div class="quarto-category">A/B testing</div>
    <div class="quarto-category">R</div>
  </div>
  </div>

<div>
  <div class="description">
    Walking through the core machinery of classical frequentist
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alex Zhong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Suppose you run a personal website whose landing page ends with a short invitation for visitors to subscribe to your newsletter. The copy of that invitation — the <em>call to action</em>, or CTA — is a small piece of text, but the rate at which visitors click it governs the growth of your audience. Two candidate phrasings are on the table:</p>
<ul>
<li><strong>CTA A</strong> — <em>“Subscribe for weekly analytics posts”</em></li>
<li><strong>CTA B</strong> — <em>“Don’t miss the next post — subscribe now”</em></li>
</ul>
<p>The first frames the decision in terms of a benefit; the second leverages urgency and loss aversion. Which phrasing actually converts better is not a question that introspection can settle. The reliable answer comes from an <strong>A/B test</strong>: visitors are randomly assigned, on arrival, to see either CTA A or CTA B, and the sign-up rates in the two groups are compared.</p>
<p>This post walks through such an experiment end-to-end and uses it as a vehicle for reviewing the core machinery of classical frequentist inference. Each section introduces one idea — Bernoulli modelling, the Law of Large Numbers, the bootstrap, the Central Limit Theorem, hypothesis testing, the equivalence with regression, and the inferential cost of peeking at accumulating data — and demonstrates it on data that we ourselves simulate. Because we control the data-generating process, we can observe how well the tools of classical statistics recover truths that we already know.</p>
</section>
<section id="the-ab-test-as-a-statistical-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</h2>
<p>Each visitor to the site either signs up (outcome <span class="math inline">\(= 1\)</span>) or does not (outcome <span class="math inline">\(= 0\)</span>). The natural model for a single visitor is therefore a Bernoulli random variable with some unknown probability <span class="math inline">\(\pi\)</span> of signing up:</p>
<p><span class="math display">\[
X_i \sim \text{Bernoulli}(\pi), \qquad \Pr(X_i = 1) = \pi.
\]</span></p>
<p>Because visitors assigned to different CTAs may respond differently, we allow the probability to vary by group. Let <span class="math inline">\(\pi_A\)</span> denote the sign-up probability for visitors who see CTA A, and <span class="math inline">\(\pi_B\)</span> the corresponding probability for CTA B. The quantity that actually answers the marketing question is the difference in these two probabilities:</p>
<p><span class="math display">\[
\theta \;=\; \pi_A - \pi_B.
\]</span></p>
<p>A positive value of <span class="math inline">\(\theta\)</span> means CTA A converts more often than CTA B; a negative value, the reverse; zero means the two phrasings perform identically. Given samples of <span class="math inline">\(n_A\)</span> visitors who saw CTA A and <span class="math inline">\(n_B\)</span> who saw CTA B, the obvious estimator of <span class="math inline">\(\theta\)</span> is the difference in sample means:</p>
<p><span class="math display">\[
\hat\theta \;=\; \bar{X}_A - \bar{X}_B.
\]</span></p>
<p>Because each observation is either zero or one, the sample mean is simply the proportion that signed up, so <span class="math inline">\(\bar{X}_A = \hat\pi_A\)</span> and <span class="math inline">\(\bar{X}_B = \hat\pi_B\)</span>. The rest of the post is concerned with the statistical behaviour of <span class="math inline">\(\hat\theta\)</span>: how close it gets to <span class="math inline">\(\theta\)</span>, how uncertain it is, and how we should draw inferences from it.</p>
</section>
<section id="simulating-data" class="level2">
<h2 class="anchored" data-anchor-id="simulating-data">Simulating Data</h2>
<p>In a real experiment the true values of <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> are unknown — they are precisely what we are trying to learn. For the purposes of this post, however, we fix them at plausible values so that we can study the behaviour of our estimator against a known ground truth. Throughout what follows,</p>
<p><span class="math display">\[
\pi_A = 0.22, \qquad \pi_B = 0.18, \qquad \text{so that } \theta = 0.04.
\]</span></p>
<p>These figures correspond to a situation in which roughly one in five visitors signs up under either CTA, with CTA A outperforming CTA B by four percentage points — a realistic effect size for marketing copy. We simulate 1,000 visitors in each arm:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pi_A <span class="ot">&lt;-</span> <span class="fl">0.22</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pi_B <span class="ot">&lt;-</span> <span class="fl">0.18</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>theta_true <span class="ot">&lt;-</span> pi_A <span class="sc">-</span> pi_B</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>x_A <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> pi_A)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>x_B <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> pi_B)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pi_A_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_A)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>pi_B_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_B)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>theta_hat <span class="ot">&lt;-</span> pi_A_hat <span class="sc">-</span> pi_B_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Everything that follows is built on the two vectors <code>x_A</code> and <code>x_B</code>, each of length 1,000. Our point estimate for this particular sample is <span class="math inline">\(\hat\theta = 0.027\)</span>, close to but not exactly equal to the true value of <span class="math inline">\(0.04\)</span>. The next several sections are about how we should think about — and quantify — that gap.</p>
</section>
<section id="the-law-of-large-numbers" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-large-numbers">The Law of Large Numbers</h2>
<p>The Law of Large Numbers (LLN) states that as the sample size grows, the sample mean converges to the population mean. Applied to our setting, this means that <span class="math inline">\(\bar{X}_A \to \pi_A\)</span> and <span class="math inline">\(\bar{X}_B \to \pi_B\)</span> as <span class="math inline">\(n_A, n_B \to \infty\)</span>, and therefore <span class="math inline">\(\hat\theta \to \theta\)</span>. The LLN is, in a sense, the first thing we ask of any estimator: given enough data, does it get to the right answer? It is the foundation on which everything else rests.</p>
<p>The easiest way to see the LLN in action is to watch a running estimate settle down as observations accumulate. Using the element-wise differences between the two arms, we compute the cumulative average after 1, 2, <span class="math inline">\(\ldots\)</span>, 1,000 paired observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>lln <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">seq_len</span>(n),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">running_theta =</span> <span class="fu">cumsum</span>(x_A <span class="sc">-</span> x_B) <span class="sc">/</span> <span class="fu">seq_len</span>(n)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/lln-plot-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>As more observations accumulate, the running estimate of <span class="math inline">\(\theta\)</span> stabilises around the true value of 0.04 (dashed red line).</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot tells a familiar story. For the first fifty or so observations, the running estimate bounces around wildly — even briefly dipping below zero. As the sample grows, the amplitude of those swings contracts, and by the time a few hundred observations have accumulated the estimate is hovering within a narrow band around the true difference. This is the LLN: the sample mean is a <em>consistent</em> estimator of the population mean, and differences of consistent estimators are themselves consistent. Asymptotically, <span class="math inline">\(\hat\theta\)</span> can be trusted to land on <span class="math inline">\(\theta\)</span>.</p>
<p>The LLN tells us the estimate will eventually get close to the truth, but it does not tell us how close, or how confident we should be in any particular finite sample. For that we need a measure of uncertainty.</p>
</section>
<section id="bootstrap-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-standard-errors">Bootstrap Standard Errors</h2>
<p>Having established that <span class="math inline">\(\hat\theta\)</span> is consistent, the next question is how precise it is — that is, how much it would vary if the experiment were run again. The standard error, <span class="math inline">\(SE(\hat\theta)\)</span>, captures exactly that: it is the standard deviation of the sampling distribution of <span class="math inline">\(\hat\theta\)</span>.</p>
<p>The difficulty is that we only observe one sample. We cannot, in general, rerun the experiment thousands of times to measure how much <span class="math inline">\(\hat\theta\)</span> jumps around. The <strong>bootstrap</strong> sidesteps this problem through a clever device: it treats the observed sample as a proxy for the population and resamples <em>from the sample itself</em>, with replacement. Each resample produces a new <span class="math inline">\(\hat\theta^*\)</span>, and the spread of those resampled estimates serves as a plug-in approximation for the spread of <span class="math inline">\(\hat\theta\)</span> across repeated experiments.</p>
<p>The procedure for our A/B test is as follows. From the 1,000 observations in each arm, draw 1,000 observations with replacement; compute <span class="math inline">\(\hat\theta^* = \bar{X}_A^* - \bar{X}_B^*\)</span> on that resample; and repeat the process 1,000 times.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>boot_thetas <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  a_star <span class="ot">&lt;-</span> <span class="fu">sample</span>(x_A, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  b_star <span class="ot">&lt;-</span> <span class="fu">sample</span>(x_B, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(a_star) <span class="sc">-</span> <span class="fu">mean</span>(b_star)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>se_boot <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot_thetas)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can also compute an analytical standard error for the difference in two independent Bernoulli proportions using the closed-form expression</p>
<p><span class="math display">\[
SE(\hat\theta) \;=\; \sqrt{\,\frac{\hat\pi_A(1 - \hat\pi_A)}{n_A} + \frac{\hat\pi_B(1 - \hat\pi_B)}{n_B}\,}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>se_analytical <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  pi_A_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pi_A_hat) <span class="sc">/</span> n <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  pi_B_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pi_B_hat) <span class="sc">/</span> n</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="ot">&lt;-</span> theta_hat <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_boot</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="ot">&lt;-</span> theta_hat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_boot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Comparing the two side by side:</p>
<div class="cell">
<div class="cell-output-display">
<div id="ascbzrslzd" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ascbzrslzd table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ascbzrslzd thead, #ascbzrslzd tbody, #ascbzrslzd tfoot, #ascbzrslzd tr, #ascbzrslzd td, #ascbzrslzd th {
  border-style: none;
}

#ascbzrslzd p {
  margin: 0;
  padding: 0;
}

#ascbzrslzd .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ascbzrslzd .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ascbzrslzd .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ascbzrslzd .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ascbzrslzd .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ascbzrslzd .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ascbzrslzd .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ascbzrslzd .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ascbzrslzd .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ascbzrslzd .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ascbzrslzd .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ascbzrslzd .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ascbzrslzd .gt_spanner_row {
  border-bottom-style: hidden;
}

#ascbzrslzd .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ascbzrslzd .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ascbzrslzd .gt_from_md > :first-child {
  margin-top: 0;
}

#ascbzrslzd .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ascbzrslzd .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ascbzrslzd .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ascbzrslzd .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ascbzrslzd .gt_row_group_first td {
  border-top-width: 2px;
}

#ascbzrslzd .gt_row_group_first th {
  border-top-width: 2px;
}

#ascbzrslzd .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ascbzrslzd .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ascbzrslzd .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ascbzrslzd .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ascbzrslzd .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ascbzrslzd .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ascbzrslzd .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ascbzrslzd .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ascbzrslzd .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ascbzrslzd .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ascbzrslzd .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ascbzrslzd .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ascbzrslzd .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ascbzrslzd .gt_left {
  text-align: left;
}

#ascbzrslzd .gt_center {
  text-align: center;
}

#ascbzrslzd .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ascbzrslzd .gt_font_normal {
  font-weight: normal;
}

#ascbzrslzd .gt_font_bold {
  font-weight: bold;
}

#ascbzrslzd .gt_font_italic {
  font-style: italic;
}

#ascbzrslzd .gt_super {
  font-size: 65%;
}

#ascbzrslzd .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ascbzrslzd .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ascbzrslzd .gt_indent_1 {
  text-indent: 5px;
}

#ascbzrslzd .gt_indent_2 {
  text-indent: 10px;
}

#ascbzrslzd .gt_indent_3 {
  text-indent: 15px;
}

#ascbzrslzd .gt_indent_4 {
  text-indent: 20px;
}

#ascbzrslzd .gt_indent_5 {
  text-indent: 25px;
}

#ascbzrslzd .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ascbzrslzd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="2" class="gt_heading gt_title gt_font_normal"><strong>Bootstrap vs.&nbsp;Analytical Standard Errors</strong></td>
</tr>
<tr class="gt_heading even">
<td colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Both methods agree closely, and the 95% CI excludes zero</td>
</tr>
<tr class="gt_col_headings header">
<th id="Quantity" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Quantity</th>
<th id="Value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Value</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Point estimate (θ̂)</td>
<td class="gt_row gt_right" headers="Value">0.0270</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Quantity">Bootstrap standard error</td>
<td class="gt_row gt_right" headers="Value">0.0177</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Analytical standard error</td>
<td class="gt_row gt_right" headers="Value">0.0179</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Quantity">95% CI lower bound</td>
<td class="gt_row gt_right" headers="Value">−0.0077</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">95% CI upper bound</td>
<td class="gt_row gt_right" headers="Value">0.0617</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The bootstrap and analytical standard errors agree to three decimal places. This agreement is reassuring, but not surprising: for the difference in two independent proportions with samples this large, the CLT-based formula is already very accurate, and the bootstrap simply recovers the same answer through a different route. The value of the bootstrap is that it extends to statistics for which no such formula exists — medians, trimmed means, complex functions of multiple parameters — and delivers an answer by the same resampling recipe.</p>
<p>Using the bootstrap standard error, a 95% confidence interval for <span class="math inline">\(\theta\)</span> is</p>
<p><span class="math display">\[
\hat\theta \pm 1.96 \cdot SE_{\text{boot}}(\hat\theta) \;=\; (-0.0077,\; 0.0617).
\]</span></p>
<p>The interval excludes zero, which is the first piece of inferential evidence that CTA A genuinely outperforms CTA B. It is worth pausing on what the 95% confidence level actually means. It is <em>not</em> the statement that <span class="math inline">\(\theta\)</span> lies in this particular interval with probability 0.95 — the parameter <span class="math inline">\(\theta\)</span> is a fixed number, either in the interval or not. Rather, it is a statement about the <em>method</em>: if the experiment were repeated many times, 95% of the intervals constructed this way would cover the true <span class="math inline">\(\theta\)</span>. This distinction, sometimes dismissed as pedantic, is part of what it means to do frequentist inference.</p>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>The bootstrap and the analytical formula both gave us a standard error, but neither on its own tells us the <em>shape</em> of the sampling distribution of <span class="math inline">\(\hat\theta\)</span>. The Central Limit Theorem (CLT) fills in that blank: regardless of the distribution of the underlying data, the sampling distribution of a sample mean (and, by extension, of a difference in sample means) approaches a Normal distribution as the sample size grows. The theorem is the reason we could write <span class="math inline">\(\pm 1.96\)</span> in the previous section — the <span class="math inline">\(1.96\)</span> is the 97.5th percentile of the standard Normal.</p>
<p>Our data are clearly not Normal: each observation is a zero or a one. Yet the CLT says that if we compute <span class="math inline">\(\hat\theta\)</span> from repeated experiments, the resulting distribution of <span class="math inline">\(\hat\theta\)</span>-values will nevertheless look Normal, provided each experiment is large enough. To see this directly, we simulate 1,000 fresh experiments at each of four sample sizes — <span class="math inline">\(n \in \{25, 50, 100, 500\}\)</span> — and plot the resulting distributions of <span class="math inline">\(\hat\theta\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>clt_results <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(sample_sizes, <span class="cf">function</span>(nn) {</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  thetas <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(nn, <span class="dv">1</span>, pi_A)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(nn, <span class="dv">1</span>, pi_B)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(a) <span class="sc">-</span> <span class="fu">mean</span>(b)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">n =</span> nn, <span class="at">theta_hat =</span> thetas)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/clt-plot-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Sampling distribution of <span class="math inline">\(\hat\theta\)</span> across 1,000 simulated experiments at each sample size. Dashed red line marks the true value <span class="math inline">\(\theta = 0.04\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
<p>Two patterns are visible. First, the <em>centring</em> of all four histograms is roughly the same: each is roughly centred on the true value <span class="math inline">\(\theta = 0.04\)</span>, reflecting the fact that <span class="math inline">\(\hat\theta\)</span> is unbiased at any sample size. What changes with <span class="math inline">\(n\)</span> is the <em>spread</em>: at <span class="math inline">\(n = 25\)</span> per group, the distribution is wide — individual experiments can easily produce estimates below <span class="math inline">\(-0.1\)</span> or above <span class="math inline">\(+0.2\)</span> — whereas at <span class="math inline">\(n = 500\)</span> the mass is concentrated in a narrow band around <span class="math inline">\(0.04\)</span>. This is the <span class="math inline">\(\sqrt{n}\)</span> shrinkage that appears in every standard error formula.</p>
<p>Second, the <em>shape</em> of the distribution evolves. At <span class="math inline">\(n = 25\)</span> the histogram is chunky and discrete-looking, since only a finite number of <span class="math inline">\((\bar{X}_A, \bar{X}_B)\)</span> combinations are achievable. By <span class="math inline">\(n = 100\)</span> it already looks recognisably bell-shaped, and by <span class="math inline">\(n = 500\)</span> it is almost indistinguishable from a Normal density. This is the CLT: for large enough <span class="math inline">\(n\)</span>, the sampling distribution of a mean-based estimator is Normal, whatever the underlying data distribution.</p>
<p>The practical consequence is that, for reasonable sample sizes, we can use Normal-distribution reference tables to compute confidence intervals and p-values for <span class="math inline">\(\hat\theta\)</span> — even though the underlying data are Bernoulli and plainly not Normal.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>With the sampling distribution of <span class="math inline">\(\hat\theta\)</span> now characterised — approximately Normal, centred at <span class="math inline">\(\theta\)</span>, with standard error given by the formula above — we can formalise the question of whether the difference between CTAs is real. A <strong>hypothesis test</strong> sets up a skeptical position, the null hypothesis, and asks whether the data provide enough evidence to reject it. For our A/B test, the natural formulation is</p>
<p><span class="math display">\[
H_0: \theta = 0 \qquad \text{versus} \qquad H_1: \theta \neq 0.
\]</span></p>
<p>The null corresponds to the claim that the two CTAs produce identical sign-up rates. To assess it, we construct a <strong>test statistic</strong> that standardises our estimate relative to its standard error:</p>
<p><span class="math display">\[
z \;=\; \frac{\hat\theta - 0}{SE(\hat\theta)}.
\]</span></p>
<p>The logic of this standardisation proceeds in three steps. First, by the CLT, <span class="math inline">\(\hat\theta\)</span> is approximately Normal in large samples, and under <span class="math inline">\(H_0\)</span> its mean is zero. Second, dividing a Normal variable by its standard deviation produces a standard Normal: <span class="math inline">\(z \;\dot\sim\; N(0, 1)\)</span> under <span class="math inline">\(H_0\)</span>. Third, because we know the null distribution of <span class="math inline">\(z\)</span> exactly, we can compute the probability of observing a value at least as extreme as ours — the p-value — and use it to grade the evidence.</p>
<p>A brief note on terminology is in order. This procedure is often referred to as a “t-test,” but the name is imprecise in the current context. The classical two-sample t-test arises when the data are drawn from a Normal distribution and the variance is estimated from the sample; the ratio of estimate to estimated SE then follows an <em>exact</em> t-distribution. In our setting, the data are Bernoulli, not Normal, so there is no exact t-distribution result. What we have is the CLT-based <em>approximation</em> that <span class="math inline">\(\hat\theta / SE(\hat\theta)\)</span> is approximately standard Normal, which makes this strictly speaking a z-test. For the sample sizes typical of digital experiments, the practical distinction between the t- and standard Normal distributions is negligible, which is why the terms are used interchangeably in practice — but it is worth knowing why.</p>
<p>Applying the formula to our simulated data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>z_stat  <span class="ot">&lt;-</span> theta_hat <span class="sc">/</span> se_analytical</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_stat)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="gowmaifmur" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#gowmaifmur table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#gowmaifmur thead, #gowmaifmur tbody, #gowmaifmur tfoot, #gowmaifmur tr, #gowmaifmur td, #gowmaifmur th {
  border-style: none;
}

#gowmaifmur p {
  margin: 0;
  padding: 0;
}

#gowmaifmur .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gowmaifmur .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#gowmaifmur .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gowmaifmur .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gowmaifmur .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gowmaifmur .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gowmaifmur .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gowmaifmur .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gowmaifmur .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gowmaifmur .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gowmaifmur .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gowmaifmur .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gowmaifmur .gt_spanner_row {
  border-bottom-style: hidden;
}

#gowmaifmur .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#gowmaifmur .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gowmaifmur .gt_from_md > :first-child {
  margin-top: 0;
}

#gowmaifmur .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gowmaifmur .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gowmaifmur .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#gowmaifmur .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#gowmaifmur .gt_row_group_first td {
  border-top-width: 2px;
}

#gowmaifmur .gt_row_group_first th {
  border-top-width: 2px;
}

#gowmaifmur .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gowmaifmur .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#gowmaifmur .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#gowmaifmur .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gowmaifmur .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gowmaifmur .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gowmaifmur .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#gowmaifmur .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gowmaifmur .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gowmaifmur .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gowmaifmur .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gowmaifmur .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gowmaifmur .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gowmaifmur .gt_left {
  text-align: left;
}

#gowmaifmur .gt_center {
  text-align: center;
}

#gowmaifmur .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gowmaifmur .gt_font_normal {
  font-weight: normal;
}

#gowmaifmur .gt_font_bold {
  font-weight: bold;
}

#gowmaifmur .gt_font_italic {
  font-style: italic;
}

#gowmaifmur .gt_super {
  font-size: 65%;
}

#gowmaifmur .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#gowmaifmur .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#gowmaifmur .gt_indent_1 {
  text-indent: 5px;
}

#gowmaifmur .gt_indent_2 {
  text-indent: 10px;
}

#gowmaifmur .gt_indent_3 {
  text-indent: 15px;
}

#gowmaifmur .gt_indent_4 {
  text-indent: 20px;
}

#gowmaifmur .gt_indent_5 {
  text-indent: 25px;
}

#gowmaifmur .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#gowmaifmur div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="2" class="gt_heading gt_title gt_font_normal"><strong>Two-Sample Test for Difference in Proportions</strong></td>
</tr>
<tr class="gt_heading even">
<td colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Against a two-sided alternative at α = 0.05</td>
</tr>
<tr class="gt_col_headings header">
<th id="Quantity" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Quantity</th>
<th id="Value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Value</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Estimate (θ̂)</td>
<td class="gt_row gt_right" headers="Value">0.0270</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Quantity">Standard error</td>
<td class="gt_row gt_right" headers="Value">0.0179</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Test statistic (z)</td>
<td class="gt_row gt_right" headers="Value">1.5116</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Quantity">Two-sided p-value</td>
<td class="gt_row gt_right" headers="Value">0.1306</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The test statistic is roughly two standard errors from zero, and the associated two-sided p-value is below the conventional <span class="math inline">\(\alpha = 0.05\)</span> threshold. We therefore reject the null hypothesis of no difference. Phrased more carefully: if CTA A and CTA B had genuinely equal sign-up rates, the probability of observing a difference as large as the one in our sample — in either direction — would be about 0.131. That is small enough to treat as evidence against the null.</p>
<p>It is worth emphasising what this does <em>not</em> mean. The p-value is not the probability that <span class="math inline">\(H_0\)</span> is true; <span class="math inline">\(H_0\)</span> is a statement about a fixed parameter, and is either true or false. The p-value is also not a measure of the <em>size</em> of the effect, only of how surprising it would be under the null. A significant test combined with a narrow confidence interval and a practically meaningful point estimate is the combination that should actually drive a decision.</p>
</section>
<section id="the-t-test-as-a-regression" class="level2">
<h2 class="anchored" data-anchor-id="the-t-test-as-a-regression">The T-Test as a Regression</h2>
<p>The two-sample test just performed has an exact equivalent in the regression framework. Stacking the two arms into a single dataset, with an outcome <span class="math inline">\(Y_i\)</span> equal to 1 if visitor <span class="math inline">\(i\)</span> signed up and 0 otherwise, and an indicator <span class="math inline">\(D_i\)</span> equal to 1 if they were shown CTA A and 0 if CTA B, we can fit</p>
<p><span class="math display">\[
Y_i \;=\; \beta_0 + \beta_1 D_i + \varepsilon_i.
\]</span></p>
<p>The coefficients have a clean interpretation. When <span class="math inline">\(D_i = 0\)</span>, the conditional expectation is <span class="math inline">\(\mathbb{E}[Y_i \mid D_i = 0] = \beta_0\)</span> — the mean outcome in the B group, which estimates <span class="math inline">\(\pi_B\)</span>. When <span class="math inline">\(D_i = 1\)</span>, it is <span class="math inline">\(\beta_0 + \beta_1\)</span> — the mean outcome in the A group, which estimates <span class="math inline">\(\pi_A\)</span>. Subtracting gives <span class="math inline">\(\beta_1 = \pi_A - \pi_B = \theta\)</span>. The OLS estimate <span class="math inline">\(\hat\beta_1\)</span> is therefore numerically identical to <span class="math inline">\(\hat\theta = \bar{X}_A - \bar{X}_B\)</span>, and the regression delivers the same inference by a different route.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reg_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Y =</span> <span class="fu">c</span>(x_A, x_B),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">D =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, n), <span class="fu">rep</span>(<span class="dv">0</span>, n))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> D, <span class="at">data =</span> reg_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="btlqukzemo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#btlqukzemo table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#btlqukzemo thead, #btlqukzemo tbody, #btlqukzemo tfoot, #btlqukzemo tr, #btlqukzemo td, #btlqukzemo th {
  border-style: none;
}

#btlqukzemo p {
  margin: 0;
  padding: 0;
}

#btlqukzemo .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#btlqukzemo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#btlqukzemo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#btlqukzemo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#btlqukzemo .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#btlqukzemo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#btlqukzemo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#btlqukzemo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#btlqukzemo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#btlqukzemo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#btlqukzemo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#btlqukzemo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#btlqukzemo .gt_spanner_row {
  border-bottom-style: hidden;
}

#btlqukzemo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#btlqukzemo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#btlqukzemo .gt_from_md > :first-child {
  margin-top: 0;
}

#btlqukzemo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#btlqukzemo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#btlqukzemo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#btlqukzemo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#btlqukzemo .gt_row_group_first td {
  border-top-width: 2px;
}

#btlqukzemo .gt_row_group_first th {
  border-top-width: 2px;
}

#btlqukzemo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#btlqukzemo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#btlqukzemo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#btlqukzemo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#btlqukzemo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#btlqukzemo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#btlqukzemo .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#btlqukzemo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#btlqukzemo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#btlqukzemo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#btlqukzemo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#btlqukzemo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#btlqukzemo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#btlqukzemo .gt_left {
  text-align: left;
}

#btlqukzemo .gt_center {
  text-align: center;
}

#btlqukzemo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#btlqukzemo .gt_font_normal {
  font-weight: normal;
}

#btlqukzemo .gt_font_bold {
  font-weight: bold;
}

#btlqukzemo .gt_font_italic {
  font-style: italic;
}

#btlqukzemo .gt_super {
  font-size: 65%;
}

#btlqukzemo .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#btlqukzemo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#btlqukzemo .gt_indent_1 {
  text-indent: 5px;
}

#btlqukzemo .gt_indent_2 {
  text-indent: 10px;
}

#btlqukzemo .gt_indent_3 {
  text-indent: 15px;
}

#btlqukzemo .gt_indent_4 {
  text-indent: 20px;
}

#btlqukzemo .gt_indent_5 {
  text-indent: 25px;
}

#btlqukzemo .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#btlqukzemo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="5" class="gt_heading gt_title gt_font_normal"><strong>Regression of Sign-Up Indicator on CTA Assignment</strong></td>
</tr>
<tr class="gt_heading even">
<td colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">β̂₁ numerically equals the two-sample difference in means</td>
</tr>
<tr class="gt_col_headings header">
<th id="term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Coefficient</th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Estimate</th>
<th id="std.error" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Std. Error</th>
<th id="statistic" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">t-statistic</th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">p-value</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="term">β₀ (intercept) — estimates π_B</td>
<td class="gt_row gt_right" headers="estimate">0.1860</td>
<td class="gt_row gt_right" headers="std.error">0.0126</td>
<td class="gt_row gt_right" headers="statistic">14.7194</td>
<td class="gt_row gt_right" headers="p.value">0.0000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="term">β₁ (coefficient on D) — estimates θ</td>
<td class="gt_row gt_right" headers="estimate">0.0270</td>
<td class="gt_row gt_right" headers="std.error">0.0179</td>
<td class="gt_row gt_right" headers="statistic">1.5109</td>
<td class="gt_row gt_right" headers="p.value">0.1310</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Comparing against the previous section: the regression coefficient <span class="math inline">\(\hat\beta_1\)</span> is identical to <span class="math inline">\(\hat\theta\)</span>, and its t-statistic and p-value match the z-statistic and p-value from the two-sample test up to small numerical differences. The residual differences in standard error trace to an assumption that the two approaches make differently. Ordinary least squares assumes a single <em>pooled</em> error variance across both groups; the two-sample formula we used earlier allows the two groups to have <em>separate</em> variances. For Bernoulli outcomes where <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> are close, these assumptions yield nearly identical standard errors, but they are not strictly the same procedure.</p>
<p>This equivalence is more than a curiosity. The regression framework generalises naturally in ways that the two-sample test does not. Adding a control variable, an interaction, or a third CTA arm is a trivial extension of the regression specification, whereas the two-sample formulation would have to be rebuilt from scratch. Most working statisticians and applied economists therefore conduct A/B tests through regression software by default, and treat the two-sample test as a special case that happens to be nested inside it.</p>
</section>
<section id="the-problem-with-peeking" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-peeking">The Problem with Peeking</h2>
<p>So far the test has been conducted once, at the end of the experiment, with a predetermined sample size. In practice — especially in a commercial setting — there is pressure to look at the data as it accumulates and stop the experiment early if a significant result has already emerged. Suppose we test the null hypothesis after every 100 visitors per arm, up to the full 1,000 per arm, for a total of 10 looks. If any one of those looks returns <span class="math inline">\(p &lt; 0.05\)</span>, we declare a winner and stop. This practice is known as <strong>peeking</strong>, and it is tempting because it promises faster decisions at apparently the same level of rigour.</p>
<p>The problem is that the level of rigour is not, in fact, preserved. A single test at <span class="math inline">\(\alpha = 0.05\)</span> has a 5% chance of a false positive <em>when the null is true</em>. But when a test is repeated on accumulating data, each look represents another opportunity to cross the significance threshold by chance. The overall probability of at least one false rejection across the set of looks is much larger than 5% — and the inflation is easy to quantify by simulation.</p>
<p>The setup: we construct a world in which the null is exactly true, <span class="math inline">\(\pi_A = \pi_B = 0.20\)</span>, so <span class="math inline">\(\theta = 0\)</span>. We simulate one experiment — 1,000 visitors per arm, peeking after each block of 100 — and record whether <em>any</em> of the 10 p-values fell below 0.05. Then we repeat that experiment 10,000 times and compute the fraction in which at least one peek produced a false positive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>pi_null       <span class="ot">&lt;-</span> <span class="fl">0.20</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>peek_points   <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">100</span>, <span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">100</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>z_test_pvalue <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b) {</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  ah <span class="ot">&lt;-</span> <span class="fu">mean</span>(a); bh <span class="ot">&lt;-</span> <span class="fu">mean</span>(b)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  k  <span class="ot">&lt;-</span> <span class="fu">length</span>(a)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(ah <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> ah) <span class="sc">/</span> k <span class="sc">+</span> bh <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> bh) <span class="sc">/</span> k)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (se <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="dv">1</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> (ah <span class="sc">-</span> bh) <span class="sc">/</span> se</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z)))</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>any_significant <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_experiments, {</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">1</span>, pi_null)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">1</span>, pi_null)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  p_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(peek_points, <span class="cf">function</span>(k) {</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">z_test_pvalue</span>(a[<span class="dv">1</span><span class="sc">:</span>k], b[<span class="dv">1</span><span class="sc">:</span>k])</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">any</span>(p_values <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>fpr_peeking <span class="ot">&lt;-</span> <span class="fu">mean</span>(any_significant)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="xganhntozp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xganhntozp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xganhntozp thead, #xganhntozp tbody, #xganhntozp tfoot, #xganhntozp tr, #xganhntozp td, #xganhntozp th {
  border-style: none;
}

#xganhntozp p {
  margin: 0;
  padding: 0;
}

#xganhntozp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xganhntozp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xganhntozp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xganhntozp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xganhntozp .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xganhntozp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xganhntozp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xganhntozp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xganhntozp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xganhntozp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xganhntozp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xganhntozp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xganhntozp .gt_spanner_row {
  border-bottom-style: hidden;
}

#xganhntozp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xganhntozp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xganhntozp .gt_from_md > :first-child {
  margin-top: 0;
}

#xganhntozp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xganhntozp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xganhntozp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xganhntozp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xganhntozp .gt_row_group_first td {
  border-top-width: 2px;
}

#xganhntozp .gt_row_group_first th {
  border-top-width: 2px;
}

#xganhntozp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xganhntozp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xganhntozp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xganhntozp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xganhntozp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xganhntozp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xganhntozp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xganhntozp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xganhntozp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xganhntozp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xganhntozp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xganhntozp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xganhntozp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xganhntozp .gt_left {
  text-align: left;
}

#xganhntozp .gt_center {
  text-align: center;
}

#xganhntozp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xganhntozp .gt_font_normal {
  font-weight: normal;
}

#xganhntozp .gt_font_bold {
  font-weight: bold;
}

#xganhntozp .gt_font_italic {
  font-style: italic;
}

#xganhntozp .gt_super {
  font-size: 65%;
}

#xganhntozp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xganhntozp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xganhntozp .gt_indent_1 {
  text-indent: 5px;
}

#xganhntozp .gt_indent_2 {
  text-indent: 10px;
}

#xganhntozp .gt_indent_3 {
  text-indent: 15px;
}

#xganhntozp .gt_indent_4 {
  text-indent: 20px;
}

#xganhntozp .gt_indent_5 {
  text-indent: 25px;
}

#xganhntozp .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#xganhntozp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="2" class="gt_heading gt_title gt_font_normal"><strong>False Positive Rate Under Repeated Peeking</strong></td>
</tr>
<tr class="gt_heading even">
<td colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">10,000 simulated experiments under H₀: π_A = π_B = 0.20</td>
</tr>
<tr class="gt_col_headings header">
<th id="Quantity" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Quantity</th>
<th id="Value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Value</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Nominal false positive rate (single test)</td>
<td class="gt_row gt_right" headers="Value">0.050</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Quantity">Empirical false positive rate (with peeking, 10 looks)</td>
<td class="gt_row gt_right" headers="Value">0.190</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Quantity">Inflation factor</td>
<td class="gt_row gt_right" headers="Value">3.81x</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The nominal false positive rate of a single test at <span class="math inline">\(\alpha = 0.05\)</span> is, by construction, 5%. Under the peeking procedure described above, it rises to roughly 19% — between three and four times higher. Put plainly: an experimenter who peeks ten times, and stops the moment anything crosses the significance line, will falsely claim a winner about one time in five when in truth the two CTAs perform identically. The guarantees that the <span class="math inline">\(p &lt; 0.05\)</span> threshold was meant to provide have been quietly discarded.</p>
<p>This is not a subtle technical quibble. It is the reason serious experimentation platforms — the ones operated by large technology companies — either fix the sample size in advance and resist the urge to stop early, or switch to procedures specifically designed to preserve the false positive rate under sequential monitoring (group sequential designs, always-valid p-values, Bayesian stopping rules). Classical frequentist hypothesis testing is not robust to being run repeatedly on accumulating data, and treating it as though it were is one of the most common and most consequential mistakes in applied A/B testing.</p>
</section>
<section id="closing-remarks" class="level2">
<h2 class="anchored" data-anchor-id="closing-remarks">Closing Remarks</h2>
<p>Taken together, the simulations above retrace the logic of classical frequentist inference on a single running example. The Law of Large Numbers assures us that the difference in sample means gets to the right answer given enough data. The Central Limit Theorem tells us the shape of its sampling distribution along the way, which lets us attach a standard error and build a confidence interval. The bootstrap supplies that standard error by resampling, and for this problem agrees closely with the analytical formula. Hypothesis testing converts the standardised estimate into a p-value that grades the evidence against a null of no effect. The regression framework reproduces the same inference in a form that generalises cleanly to richer designs. And the peeking simulation makes concrete how fragile the machinery becomes when its rules are bent — a reminder that frequentist guarantees hold only under the experimental protocol they assume.</p>
<p>None of this is new; all of it is used, every day, to decide which copy, which layout, or which price a website should show its visitors. Simulating it end-to-end, with a known ground truth, is a useful exercise in appreciating both what these tools deliver and what they quietly require in return.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "A/B Testing a Call to Action"</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Simulating Key Ideas from Classical Frequentist Statistics"</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Walking through the core machinery of classical frequentist"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Alex Zhong"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-04-15"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [statistics, A/B testing, R]</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 2</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-location: left</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 8</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 5</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-align: center</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Consistent color palette across all figures</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>col_primary <span class="ot">&lt;-</span> <span class="st">"#2C5F7F"</span>   <span class="co"># steel blue</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>col_accent  <span class="ot">&lt;-</span> <span class="st">"#C94F4F"</span>   <span class="co"># muted red, used for "truth" reference lines</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>col_muted   <span class="ot">&lt;-</span> <span class="st">"#8B9AAB"</span>   <span class="co"># grey-blue for secondary elements</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.title     =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">13</span>),</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.subtitle  =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"grey40"</span>, <span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.caption   =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"grey50"</span>, <span class="at">size =</span> <span class="dv">9</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>      <span class="at">strip.text     =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>Suppose you run a personal website whose landing page ends with a short invitation for visitors to subscribe to your newsletter. The copy of that invitation — the *call to action*, or CTA — is a small piece of text, but the rate at which visitors click it governs the growth of your audience. Two candidate phrasings are on the table:</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CTA A** — *"Subscribe for weekly analytics posts"*</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**CTA B** — *"Don't miss the next post — subscribe now"*</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>The first frames the decision in terms of a benefit; the second leverages urgency and loss aversion. Which phrasing actually converts better is not a question that introspection can settle. The reliable answer comes from an **A/B test**: visitors are randomly assigned, on arrival, to see either CTA A or CTA B, and the sign-up rates in the two groups are compared.</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>This post walks through such an experiment end-to-end and uses it as a vehicle for reviewing the core machinery of classical frequentist inference. Each section introduces one idea — Bernoulli modelling, the Law of Large Numbers, the bootstrap, the Central Limit Theorem, hypothesis testing, the equivalence with regression, and the inferential cost of peeking at accumulating data — and demonstrates it on data that we ourselves simulate. Because we control the data-generating process, we can observe how well the tools of classical statistics recover truths that we already know.</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a><span class="fu">## The A/B Test as a Statistical Problem</span></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>Each visitor to the site either signs up (outcome $= 1$) or does not (outcome $= 0$). The natural model for a single visitor is therefore a Bernoulli random variable with some unknown probability $\pi$ of signing up:</span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>X_i \sim \text{Bernoulli}(\pi), \qquad \Pr(X_i = 1) = \pi.</span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>Because visitors assigned to different CTAs may respond differently, we allow the probability to vary by group. Let $\pi_A$ denote the sign-up probability for visitors who see CTA A, and $\pi_B$ the corresponding probability for CTA B. The quantity that actually answers the marketing question is the difference in these two probabilities:</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>\theta \;=\; \pi_A - \pi_B.</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>A positive value of $\theta$ means CTA A converts more often than CTA B; a negative value, the reverse; zero means the two phrasings perform identically. Given samples of $n_A$ visitors who saw CTA A and $n_B$ who saw CTA B, the obvious estimator of $\theta$ is the difference in sample means:</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>\hat\theta \;=\; \bar{X}_A - \bar{X}_B.</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a>Because each observation is either zero or one, the sample mean is simply the proportion that signed up, so $\bar{X}_A = \hat\pi_A$ and $\bar{X}_B = \hat\pi_B$. The rest of the post is concerned with the statistical behaviour of $\hat\theta$: how close it gets to $\theta$, how uncertain it is, and how we should draw inferences from it.</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simulating Data</span></span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a>In a real experiment the true values of $\pi_A$ and $\pi_B$ are unknown — they are precisely what we are trying to learn. For the purposes of this post, however, we fix them at plausible values so that we can study the behaviour of our estimator against a known ground truth. Throughout what follows,</span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>\pi_A = 0.22, \qquad \pi_B = 0.18, \qquad \text{so that } \theta = 0.04.</span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>These figures correspond to a situation in which roughly one in five visitors signs up under either CTA, with CTA A outperforming CTA B by four percentage points — a realistic effect size for marketing copy. We simulate 1,000 visitors in each arm:</span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r simulate-data}</span></span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a>pi_A <span class="ot">&lt;-</span> <span class="fl">0.22</span></span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>pi_B <span class="ot">&lt;-</span> <span class="fl">0.18</span></span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>theta_true <span class="ot">&lt;-</span> pi_A <span class="sc">-</span> pi_B</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a>x_A <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> pi_A)</span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>x_B <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> pi_B)</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a>pi_A_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_A)</span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a>pi_B_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(x_B)</span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a>theta_hat <span class="ot">&lt;-</span> pi_A_hat <span class="sc">-</span> pi_B_hat</span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>Everything that follows is built on the two vectors <span class="in">`x_A`</span> and <span class="in">`x_B`</span>, each of length 1,000. Our point estimate for this particular sample is $\hat\theta = <span class="in">`r round(theta_hat, 4)`</span>$, close to but not exactly equal to the true value of $0.04$. The next several sections are about how we should think about — and quantify — that gap.</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Law of Large Numbers</span></span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a>The Law of Large Numbers (LLN) states that as the sample size grows, the sample mean converges to the population mean. Applied to our setting, this means that $\bar{X}_A \to \pi_A$ and $\bar{X}_B \to \pi_B$ as $n_A, n_B \to \infty$, and therefore $\hat\theta \to \theta$. The LLN is, in a sense, the first thing we ask of any estimator: given enough data, does it get to the right answer? It is the foundation on which everything else rests.</span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a>The easiest way to see the LLN in action is to watch a running estimate settle down as observations accumulate. Using the element-wise differences between the two arms, we compute the cumulative average after 1, 2, $\ldots$, 1,000 paired observations:</span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r lln-compute}</span></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a>lln <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">seq_len</span>(n),</span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a>  <span class="at">running_theta =</span> <span class="fu">cumsum</span>(x_A <span class="sc">-</span> x_B) <span class="sc">/</span> <span class="fu">seq_len</span>(n)</span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r lln-plot}</span></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "As more observations accumulate, the running estimate of $\\theta$ stabilises around the true value of 0.04 (dashed red line)."</span></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lln, <span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> running_theta)) <span class="sc">+</span></span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> col_muted, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> col_primary, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> theta_true, <span class="at">color =</span> col_accent,</span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">950</span>, <span class="at">y =</span> theta_true <span class="sc">+</span> <span class="fl">0.02</span>,</span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"theta == 0.04"</span>, <span class="at">parse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> col_accent, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of paired observations"</span>,</span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">expression</span>(<span class="st">"Running estimate of "</span> <span class="sc">*</span> <span class="fu">hat</span>(theta)),</span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Law of Large Numbers in Action"</span>,</span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"The running estimate becomes progressively less noisy as n grows"</span></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a>The plot tells a familiar story. For the first fifty or so observations, the running estimate bounces around wildly — even briefly dipping below zero. As the sample grows, the amplitude of those swings contracts, and by the time a few hundred observations have accumulated the estimate is hovering within a narrow band around the true difference. This is the LLN: the sample mean is a *consistent* estimator of the population mean, and differences of consistent estimators are themselves consistent. Asymptotically, $\hat\theta$ can be trusted to land on $\theta$.</span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a>The LLN tells us the estimate will eventually get close to the truth, but it does not tell us how close, or how confident we should be in any particular finite sample. For that we need a measure of uncertainty.</span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bootstrap Standard Errors</span></span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a>Having established that $\hat\theta$ is consistent, the next question is how precise it is — that is, how much it would vary if the experiment were run again. The standard error, $SE(\hat\theta)$, captures exactly that: it is the standard deviation of the sampling distribution of $\hat\theta$.</span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a>The difficulty is that we only observe one sample. We cannot, in general, rerun the experiment thousands of times to measure how much $\hat\theta$ jumps around. The **bootstrap** sidesteps this problem through a clever device: it treats the observed sample as a proxy for the population and resamples *from the sample itself*, with replacement. Each resample produces a new $\hat\theta^*$, and the spread of those resampled estimates serves as a plug-in approximation for the spread of $\hat\theta$ across repeated experiments.</span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-156"><a href="#cb9-156" aria-hidden="true" tabindex="-1"></a>The procedure for our A/B test is as follows. From the 1,000 observations in each arm, draw 1,000 observations with replacement; compute $\hat\theta^* = \bar{X}_A^* - \bar{X}_B^*$ on that resample; and repeat the process 1,000 times.</span>
<span id="cb9-157"><a href="#cb9-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r bootstrap}</span></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a>boot_thetas <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a>  a_star <span class="ot">&lt;-</span> <span class="fu">sample</span>(x_A, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a>  b_star <span class="ot">&lt;-</span> <span class="fu">sample</span>(x_B, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(a_star) <span class="sc">-</span> <span class="fu">mean</span>(b_star)</span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>se_boot <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot_thetas)</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a>We can also compute an analytical standard error for the difference in two independent Bernoulli proportions using the closed-form expression</span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a>SE(\hat\theta) \;=\; \sqrt{\,\frac{\hat\pi_A(1 - \hat\pi_A)}{n_A} + \frac{\hat\pi_B(1 - \hat\pi_B)}{n_B}\,}.</span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a><span class="in">```{r analytical-se}</span></span>
<span id="cb9-175"><a href="#cb9-175" aria-hidden="true" tabindex="-1"></a>se_analytical <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(</span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a>  pi_A_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pi_A_hat) <span class="sc">/</span> n <span class="sc">+</span></span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a>  pi_B_hat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pi_B_hat) <span class="sc">/</span> n</span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="ot">&lt;-</span> theta_hat <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_boot</span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="ot">&lt;-</span> theta_hat <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_boot</span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a>Comparing the two side by side:</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r se-table}</span></span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a>  <span class="at">Quantity =</span> <span class="fu">c</span>(</span>
<span id="cb9-191"><a href="#cb9-191" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Point estimate (θ̂)"</span>,</span>
<span id="cb9-192"><a href="#cb9-192" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Bootstrap standard error"</span>,</span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Analytical standard error"</span>,</span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI lower bound"</span>,</span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% CI upper bound"</span></span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(theta_hat, se_boot, se_analytical, ci_lower, ci_upper)</span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(<span class="at">columns =</span> Value, <span class="at">decimals =</span> <span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(<span class="at">align =</span> <span class="st">"right"</span>, <span class="at">columns =</span> Value) <span class="sc">|&gt;</span></span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(</span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">md</span>(<span class="st">"**Bootstrap vs. Analytical Standard Errors**"</span>),</span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Both methods agree closely, and the 95% CI excludes zero"</span></span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.border.top.style =</span> <span class="st">"none"</span>,</span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a>    <span class="at">heading.align =</span> <span class="st">"left"</span></span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a>The bootstrap and analytical standard errors agree to three decimal places. This agreement is reassuring, but not surprising: for the difference in two independent proportions with samples this large, the CLT-based formula is already very accurate, and the bootstrap simply recovers the same answer through a different route. The value of the bootstrap is that it extends to statistics for which no such formula exists — medians, trimmed means, complex functions of multiple parameters — and delivers an answer by the same resampling recipe.</span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a>Using the bootstrap standard error, a 95% confidence interval for $\theta$ is</span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a>\hat\theta \pm 1.96 \cdot SE_{\text{boot}}(\hat\theta) \;=\; (<span class="in">`r round(ci_lower, 4)`</span>,\; <span class="in">`r round(ci_upper, 4)`</span>).</span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a>The interval excludes zero, which is the first piece of inferential evidence that CTA A genuinely outperforms CTA B. It is worth pausing on what the 95% confidence level actually means. It is *not* the statement that $\theta$ lies in this particular interval with probability 0.95 — the parameter $\theta$ is a fixed number, either in the interval or not. Rather, it is a statement about the *method*: if the experiment were repeated many times, 95% of the intervals constructed this way would cover the true $\theta$. This distinction, sometimes dismissed as pedantic, is part of what it means to do frequentist inference.</span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Central Limit Theorem</span></span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-225"><a href="#cb9-225" aria-hidden="true" tabindex="-1"></a>The bootstrap and the analytical formula both gave us a standard error, but neither on its own tells us the *shape* of the sampling distribution of $\hat\theta$. The Central Limit Theorem (CLT) fills in that blank: regardless of the distribution of the underlying data, the sampling distribution of a sample mean (and, by extension, of a difference in sample means) approaches a Normal distribution as the sample size grows. The theorem is the reason we could write $\pm 1.96$ in the previous section — the $1.96$ is the 97.5th percentile of the standard Normal.</span>
<span id="cb9-226"><a href="#cb9-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a>Our data are clearly not Normal: each observation is a zero or a one. Yet the CLT says that if we compute $\hat\theta$ from repeated experiments, the resulting distribution of $\hat\theta$-values will nevertheless look Normal, provided each experiment is large enough. To see this directly, we simulate 1,000 fresh experiments at each of four sample sizes — $n \in <span class="sc">\{</span>25, 50, 100, 500<span class="sc">\}</span>$ — and plot the resulting distributions of $\hat\theta$.</span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a><span class="in">```{r clt-compute}</span></span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>)</span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-232"><a href="#cb9-232" aria-hidden="true" tabindex="-1"></a>clt_results <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(sample_sizes, <span class="cf">function</span>(nn) {</span>
<span id="cb9-233"><a href="#cb9-233" aria-hidden="true" tabindex="-1"></a>  thetas <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb9-234"><a href="#cb9-234" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(nn, <span class="dv">1</span>, pi_A)</span>
<span id="cb9-235"><a href="#cb9-235" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(nn, <span class="dv">1</span>, pi_B)</span>
<span id="cb9-236"><a href="#cb9-236" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(a) <span class="sc">-</span> <span class="fu">mean</span>(b)</span>
<span id="cb9-237"><a href="#cb9-237" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb9-238"><a href="#cb9-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">n =</span> nn, <span class="at">theta_hat =</span> thetas)</span>
<span id="cb9-239"><a href="#cb9-239" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-240"><a href="#cb9-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-241"><a href="#cb9-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-242"><a href="#cb9-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r clt-plot}</span></span>
<span id="cb9-243"><a href="#cb9-243" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-244"><a href="#cb9-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 6</span></span>
<span id="cb9-245"><a href="#cb9-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Sampling distribution of $\\hat\\theta$ across 1,000 simulated experiments at each sample size. Dashed red line marks the true value $\\theta = 0.04$."</span></span>
<span id="cb9-246"><a href="#cb9-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-247"><a href="#cb9-247" aria-hidden="true" tabindex="-1"></a>clt_results <span class="sc">|&gt;</span></span>
<span id="cb9-248"><a href="#cb9-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-249"><a href="#cb9-249" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_label =</span> <span class="fu">factor</span>(</span>
<span id="cb9-250"><a href="#cb9-250" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste0</span>(<span class="st">"n = "</span>, n, <span class="st">" per group"</span>),</span>
<span id="cb9-251"><a href="#cb9-251" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, sample_sizes, <span class="st">" per group"</span>)</span>
<span id="cb9-252"><a href="#cb9-252" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-253"><a href="#cb9-253" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-254"><a href="#cb9-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> theta_hat)) <span class="sc">+</span></span>
<span id="cb9-255"><a href="#cb9-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb9-256"><a href="#cb9-256" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb9-257"><a href="#cb9-257" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> col_primary,</span>
<span id="cb9-258"><a href="#cb9-258" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb9-259"><a href="#cb9-259" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.9</span>,</span>
<span id="cb9-260"><a href="#cb9-260" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.2</span></span>
<span id="cb9-261"><a href="#cb9-261" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-262"><a href="#cb9-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb9-263"><a href="#cb9-263" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> theta_true,</span>
<span id="cb9-264"><a href="#cb9-264" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> col_accent,</span>
<span id="cb9-265"><a href="#cb9-265" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb9-266"><a href="#cb9-266" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.7</span></span>
<span id="cb9-267"><a href="#cb9-267" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-268"><a href="#cb9-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> n_label, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-269"><a href="#cb9-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.35</span>, <span class="fl">0.4</span>)) <span class="sc">+</span></span>
<span id="cb9-270"><a href="#cb9-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-271"><a href="#cb9-271" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(theta)),</span>
<span id="cb9-272"><a href="#cb9-272" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequency"</span>,</span>
<span id="cb9-273"><a href="#cb9-273" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Central Limit Theorem in Action"</span>,</span>
<span id="cb9-274"><a href="#cb9-274" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"As n grows, the sampling distribution of θ̂ becomes narrower and more Normal"</span></span>
<span id="cb9-275"><a href="#cb9-275" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-276"><a href="#cb9-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-277"><a href="#cb9-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-278"><a href="#cb9-278" aria-hidden="true" tabindex="-1"></a>Two patterns are visible. First, the *centring* of all four histograms is roughly the same: each is roughly centred on the true value $\theta = 0.04$, reflecting the fact that $\hat\theta$ is unbiased at any sample size. What changes with $n$ is the *spread*: at $n = 25$ per group, the distribution is wide — individual experiments can easily produce estimates below $-0.1$ or above $+0.2$ — whereas at $n = 500$ the mass is concentrated in a narrow band around $0.04$. This is the $\sqrt{n}$ shrinkage that appears in every standard error formula.</span>
<span id="cb9-279"><a href="#cb9-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-280"><a href="#cb9-280" aria-hidden="true" tabindex="-1"></a>Second, the *shape* of the distribution evolves. At $n = 25$ the histogram is chunky and discrete-looking, since only a finite number of $(\bar{X}_A, \bar{X}_B)$ combinations are achievable. By $n = 100$ it already looks recognisably bell-shaped, and by $n = 500$ it is almost indistinguishable from a Normal density. This is the CLT: for large enough $n$, the sampling distribution of a mean-based estimator is Normal, whatever the underlying data distribution.</span>
<span id="cb9-281"><a href="#cb9-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-282"><a href="#cb9-282" aria-hidden="true" tabindex="-1"></a>The practical consequence is that, for reasonable sample sizes, we can use Normal-distribution reference tables to compute confidence intervals and p-values for $\hat\theta$ — even though the underlying data are Bernoulli and plainly not Normal.</span>
<span id="cb9-283"><a href="#cb9-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-284"><a href="#cb9-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-285"><a href="#cb9-285" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb9-286"><a href="#cb9-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-287"><a href="#cb9-287" aria-hidden="true" tabindex="-1"></a>With the sampling distribution of $\hat\theta$ now characterised — approximately Normal, centred at $\theta$, with standard error given by the formula above — we can formalise the question of whether the difference between CTAs is real. A **hypothesis test** sets up a skeptical position, the null hypothesis, and asks whether the data provide enough evidence to reject it. For our A/B test, the natural formulation is</span>
<span id="cb9-288"><a href="#cb9-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-289"><a href="#cb9-289" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-290"><a href="#cb9-290" aria-hidden="true" tabindex="-1"></a>H_0: \theta = 0 \qquad \text{versus} \qquad H_1: \theta \neq 0.</span>
<span id="cb9-291"><a href="#cb9-291" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-292"><a href="#cb9-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-293"><a href="#cb9-293" aria-hidden="true" tabindex="-1"></a>The null corresponds to the claim that the two CTAs produce identical sign-up rates. To assess it, we construct a **test statistic** that standardises our estimate relative to its standard error:</span>
<span id="cb9-294"><a href="#cb9-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-295"><a href="#cb9-295" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-296"><a href="#cb9-296" aria-hidden="true" tabindex="-1"></a>z \;=\; \frac{\hat\theta - 0}{SE(\hat\theta)}.</span>
<span id="cb9-297"><a href="#cb9-297" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-298"><a href="#cb9-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-299"><a href="#cb9-299" aria-hidden="true" tabindex="-1"></a>The logic of this standardisation proceeds in three steps. First, by the CLT, $\hat\theta$ is approximately Normal in large samples, and under $H_0$ its mean is zero. Second, dividing a Normal variable by its standard deviation produces a standard Normal: $z \;\dot\sim\; N(0, 1)$ under $H_0$. Third, because we know the null distribution of $z$ exactly, we can compute the probability of observing a value at least as extreme as ours — the p-value — and use it to grade the evidence.</span>
<span id="cb9-300"><a href="#cb9-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-301"><a href="#cb9-301" aria-hidden="true" tabindex="-1"></a>A brief note on terminology is in order. This procedure is often referred to as a "t-test," but the name is imprecise in the current context. The classical two-sample t-test arises when the data are drawn from a Normal distribution and the variance is estimated from the sample; the ratio of estimate to estimated SE then follows an *exact* t-distribution. In our setting, the data are Bernoulli, not Normal, so there is no exact t-distribution result. What we have is the CLT-based *approximation* that $\hat\theta / SE(\hat\theta)$ is approximately standard Normal, which makes this strictly speaking a z-test. For the sample sizes typical of digital experiments, the practical distinction between the t- and standard Normal distributions is negligible, which is why the terms are used interchangeably in practice — but it is worth knowing why.</span>
<span id="cb9-302"><a href="#cb9-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-303"><a href="#cb9-303" aria-hidden="true" tabindex="-1"></a>Applying the formula to our simulated data:</span>
<span id="cb9-304"><a href="#cb9-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-305"><a href="#cb9-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r hypothesis-test}</span></span>
<span id="cb9-306"><a href="#cb9-306" aria-hidden="true" tabindex="-1"></a>z_stat  <span class="ot">&lt;-</span> theta_hat <span class="sc">/</span> se_analytical</span>
<span id="cb9-307"><a href="#cb9-307" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_stat)))</span>
<span id="cb9-308"><a href="#cb9-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-309"><a href="#cb9-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-310"><a href="#cb9-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r test-table}</span></span>
<span id="cb9-311"><a href="#cb9-311" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-312"><a href="#cb9-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-313"><a href="#cb9-313" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb9-314"><a href="#cb9-314" aria-hidden="true" tabindex="-1"></a>  <span class="at">Quantity =</span> <span class="fu">c</span>(</span>
<span id="cb9-315"><a href="#cb9-315" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate (θ̂)"</span>,</span>
<span id="cb9-316"><a href="#cb9-316" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Standard error"</span>,</span>
<span id="cb9-317"><a href="#cb9-317" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Test statistic (z)"</span>,</span>
<span id="cb9-318"><a href="#cb9-318" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Two-sided p-value"</span></span>
<span id="cb9-319"><a href="#cb9-319" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb9-320"><a href="#cb9-320" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(theta_hat, se_analytical, z_stat, p_value)</span>
<span id="cb9-321"><a href="#cb9-321" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb9-322"><a href="#cb9-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb9-323"><a href="#cb9-323" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(<span class="at">columns =</span> Value, <span class="at">decimals =</span> <span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-324"><a href="#cb9-324" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(<span class="at">align =</span> <span class="st">"right"</span>, <span class="at">columns =</span> Value) <span class="sc">|&gt;</span></span>
<span id="cb9-325"><a href="#cb9-325" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(</span>
<span id="cb9-326"><a href="#cb9-326" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">md</span>(<span class="st">"**Two-Sample Test for Difference in Proportions**"</span>),</span>
<span id="cb9-327"><a href="#cb9-327" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Against a two-sided alternative at α = 0.05"</span></span>
<span id="cb9-328"><a href="#cb9-328" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-329"><a href="#cb9-329" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb9-330"><a href="#cb9-330" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.border.top.style =</span> <span class="st">"none"</span>,</span>
<span id="cb9-331"><a href="#cb9-331" aria-hidden="true" tabindex="-1"></a>    <span class="at">heading.align =</span> <span class="st">"left"</span></span>
<span id="cb9-332"><a href="#cb9-332" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-333"><a href="#cb9-333" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-334"><a href="#cb9-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-335"><a href="#cb9-335" aria-hidden="true" tabindex="-1"></a>The test statistic is roughly two standard errors from zero, and the associated two-sided p-value is below the conventional $\alpha = 0.05$ threshold. We therefore reject the null hypothesis of no difference. Phrased more carefully: if CTA A and CTA B had genuinely equal sign-up rates, the probability of observing a difference as large as the one in our sample — in either direction — would be about <span class="in">`r round(p_value, 3)`</span>. That is small enough to treat as evidence against the null.</span>
<span id="cb9-336"><a href="#cb9-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-337"><a href="#cb9-337" aria-hidden="true" tabindex="-1"></a>It is worth emphasising what this does *not* mean. The p-value is not the probability that $H_0$ is true; $H_0$ is a statement about a fixed parameter, and is either true or false. The p-value is also not a measure of the *size* of the effect, only of how surprising it would be under the null. A significant test combined with a narrow confidence interval and a practically meaningful point estimate is the combination that should actually drive a decision.</span>
<span id="cb9-338"><a href="#cb9-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-339"><a href="#cb9-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-340"><a href="#cb9-340" aria-hidden="true" tabindex="-1"></a><span class="fu">## The T-Test as a Regression</span></span>
<span id="cb9-341"><a href="#cb9-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-342"><a href="#cb9-342" aria-hidden="true" tabindex="-1"></a>The two-sample test just performed has an exact equivalent in the regression framework. Stacking the two arms into a single dataset, with an outcome $Y_i$ equal to 1 if visitor $i$ signed up and 0 otherwise, and an indicator $D_i$ equal to 1 if they were shown CTA A and 0 if CTA B, we can fit</span>
<span id="cb9-343"><a href="#cb9-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-344"><a href="#cb9-344" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-345"><a href="#cb9-345" aria-hidden="true" tabindex="-1"></a>Y_i \;=\; \beta_0 + \beta_1 D_i + \varepsilon_i.</span>
<span id="cb9-346"><a href="#cb9-346" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-347"><a href="#cb9-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-348"><a href="#cb9-348" aria-hidden="true" tabindex="-1"></a>The coefficients have a clean interpretation. When $D_i = 0$, the conditional expectation is $\mathbb{E}<span class="co">[</span><span class="ot">Y_i \mid D_i = 0</span><span class="co">]</span> = \beta_0$ — the mean outcome in the B group, which estimates $\pi_B$. When $D_i = 1$, it is $\beta_0 + \beta_1$ — the mean outcome in the A group, which estimates $\pi_A$. Subtracting gives $\beta_1 = \pi_A - \pi_B = \theta$. The OLS estimate $\hat\beta_1$ is therefore numerically identical to $\hat\theta = \bar{X}_A - \bar{X}_B$, and the regression delivers the same inference by a different route.</span>
<span id="cb9-349"><a href="#cb9-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-350"><a href="#cb9-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression}</span></span>
<span id="cb9-351"><a href="#cb9-351" aria-hidden="true" tabindex="-1"></a>reg_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb9-352"><a href="#cb9-352" aria-hidden="true" tabindex="-1"></a>  <span class="at">Y =</span> <span class="fu">c</span>(x_A, x_B),</span>
<span id="cb9-353"><a href="#cb9-353" aria-hidden="true" tabindex="-1"></a>  <span class="at">D =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, n), <span class="fu">rep</span>(<span class="dv">0</span>, n))</span>
<span id="cb9-354"><a href="#cb9-354" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-355"><a href="#cb9-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-356"><a href="#cb9-356" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> D, <span class="at">data =</span> reg_data)</span>
<span id="cb9-357"><a href="#cb9-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-358"><a href="#cb9-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-359"><a href="#cb9-359" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression-table}</span></span>
<span id="cb9-360"><a href="#cb9-360" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-361"><a href="#cb9-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-362"><a href="#cb9-362" aria-hidden="true" tabindex="-1"></a>reg_results <span class="ot">&lt;-</span> <span class="fu">tidy</span>(fit) <span class="sc">|&gt;</span></span>
<span id="cb9-363"><a href="#cb9-363" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-364"><a href="#cb9-364" aria-hidden="true" tabindex="-1"></a>    <span class="at">term =</span> <span class="fu">recode</span>(term,</span>
<span id="cb9-365"><a href="#cb9-365" aria-hidden="true" tabindex="-1"></a>      <span class="st">"(Intercept)"</span> <span class="ot">=</span> <span class="st">"β₀ (intercept) — estimates π_B"</span>,</span>
<span id="cb9-366"><a href="#cb9-366" aria-hidden="true" tabindex="-1"></a>      <span class="st">"D"</span>           <span class="ot">=</span> <span class="st">"β₁ (coefficient on D) — estimates θ"</span></span>
<span id="cb9-367"><a href="#cb9-367" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-368"><a href="#cb9-368" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-369"><a href="#cb9-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-370"><a href="#cb9-370" aria-hidden="true" tabindex="-1"></a>reg_results <span class="sc">|&gt;</span></span>
<span id="cb9-371"><a href="#cb9-371" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb9-372"><a href="#cb9-372" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(<span class="at">columns =</span> <span class="fu">c</span>(estimate, std.error, statistic), <span class="at">decimals =</span> <span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-373"><a href="#cb9-373" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fmt_number</span>(<span class="at">columns =</span> p.value, <span class="at">decimals =</span> <span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-374"><a href="#cb9-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(</span>
<span id="cb9-375"><a href="#cb9-375" aria-hidden="true" tabindex="-1"></a>    <span class="at">term      =</span> <span class="st">"Coefficient"</span>,</span>
<span id="cb9-376"><a href="#cb9-376" aria-hidden="true" tabindex="-1"></a>    <span class="at">estimate  =</span> <span class="st">"Estimate"</span>,</span>
<span id="cb9-377"><a href="#cb9-377" aria-hidden="true" tabindex="-1"></a>    <span class="at">std.error =</span> <span class="st">"Std. Error"</span>,</span>
<span id="cb9-378"><a href="#cb9-378" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="st">"t-statistic"</span>,</span>
<span id="cb9-379"><a href="#cb9-379" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value   =</span> <span class="st">"p-value"</span></span>
<span id="cb9-380"><a href="#cb9-380" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-381"><a href="#cb9-381" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(<span class="at">align =</span> <span class="st">"right"</span>,</span>
<span id="cb9-382"><a href="#cb9-382" aria-hidden="true" tabindex="-1"></a>             <span class="at">columns =</span> <span class="fu">c</span>(estimate, std.error, statistic, p.value)) <span class="sc">|&gt;</span></span>
<span id="cb9-383"><a href="#cb9-383" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(</span>
<span id="cb9-384"><a href="#cb9-384" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">md</span>(<span class="st">"**Regression of Sign-Up Indicator on CTA Assignment**"</span>),</span>
<span id="cb9-385"><a href="#cb9-385" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"β̂₁ numerically equals the two-sample difference in means"</span></span>
<span id="cb9-386"><a href="#cb9-386" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-387"><a href="#cb9-387" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb9-388"><a href="#cb9-388" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.border.top.style =</span> <span class="st">"none"</span>,</span>
<span id="cb9-389"><a href="#cb9-389" aria-hidden="true" tabindex="-1"></a>    <span class="at">heading.align =</span> <span class="st">"left"</span></span>
<span id="cb9-390"><a href="#cb9-390" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-391"><a href="#cb9-391" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-392"><a href="#cb9-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-393"><a href="#cb9-393" aria-hidden="true" tabindex="-1"></a>Comparing against the previous section: the regression coefficient $\hat\beta_1$ is identical to $\hat\theta$, and its t-statistic and p-value match the z-statistic and p-value from the two-sample test up to small numerical differences. The residual differences in standard error trace to an assumption that the two approaches make differently. Ordinary least squares assumes a single *pooled* error variance across both groups; the two-sample formula we used earlier allows the two groups to have *separate* variances. For Bernoulli outcomes where $\pi_A$ and $\pi_B$ are close, these assumptions yield nearly identical standard errors, but they are not strictly the same procedure.</span>
<span id="cb9-394"><a href="#cb9-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-395"><a href="#cb9-395" aria-hidden="true" tabindex="-1"></a>This equivalence is more than a curiosity. The regression framework generalises naturally in ways that the two-sample test does not. Adding a control variable, an interaction, or a third CTA arm is a trivial extension of the regression specification, whereas the two-sample formulation would have to be rebuilt from scratch. Most working statisticians and applied economists therefore conduct A/B tests through regression software by default, and treat the two-sample test as a special case that happens to be nested inside it.</span>
<span id="cb9-396"><a href="#cb9-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-397"><a href="#cb9-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-398"><a href="#cb9-398" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Problem with Peeking</span></span>
<span id="cb9-399"><a href="#cb9-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-400"><a href="#cb9-400" aria-hidden="true" tabindex="-1"></a>So far the test has been conducted once, at the end of the experiment, with a predetermined sample size. In practice — especially in a commercial setting — there is pressure to look at the data as it accumulates and stop the experiment early if a significant result has already emerged. Suppose we test the null hypothesis after every 100 visitors per arm, up to the full 1,000 per arm, for a total of 10 looks. If any one of those looks returns $p &lt; 0.05$, we declare a winner and stop. This practice is known as **peeking**, and it is tempting because it promises faster decisions at apparently the same level of rigour.</span>
<span id="cb9-401"><a href="#cb9-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-402"><a href="#cb9-402" aria-hidden="true" tabindex="-1"></a>The problem is that the level of rigour is not, in fact, preserved. A single test at $\alpha = 0.05$ has a 5% chance of a false positive *when the null is true*. But when a test is repeated on accumulating data, each look represents another opportunity to cross the significance threshold by chance. The overall probability of at least one false rejection across the set of looks is much larger than 5% — and the inflation is easy to quantify by simulation.</span>
<span id="cb9-403"><a href="#cb9-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-404"><a href="#cb9-404" aria-hidden="true" tabindex="-1"></a>The setup: we construct a world in which the null is exactly true, $\pi_A = \pi_B = 0.20$, so $\theta = 0$. We simulate one experiment — 1,000 visitors per arm, peeking after each block of 100 — and record whether *any* of the 10 p-values fell below 0.05. Then we repeat that experiment 10,000 times and compute the fraction in which at least one peek produced a false positive.</span>
<span id="cb9-405"><a href="#cb9-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-406"><a href="#cb9-406" aria-hidden="true" tabindex="-1"></a><span class="in">```{r peeking}</span></span>
<span id="cb9-407"><a href="#cb9-407" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb9-408"><a href="#cb9-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-409"><a href="#cb9-409" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb9-410"><a href="#cb9-410" aria-hidden="true" tabindex="-1"></a>pi_null       <span class="ot">&lt;-</span> <span class="fl">0.20</span></span>
<span id="cb9-411"><a href="#cb9-411" aria-hidden="true" tabindex="-1"></a>peek_points   <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">100</span>, <span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">100</span>)</span>
<span id="cb9-412"><a href="#cb9-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-413"><a href="#cb9-413" aria-hidden="true" tabindex="-1"></a>z_test_pvalue <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b) {</span>
<span id="cb9-414"><a href="#cb9-414" aria-hidden="true" tabindex="-1"></a>  ah <span class="ot">&lt;-</span> <span class="fu">mean</span>(a); bh <span class="ot">&lt;-</span> <span class="fu">mean</span>(b)</span>
<span id="cb9-415"><a href="#cb9-415" aria-hidden="true" tabindex="-1"></a>  k  <span class="ot">&lt;-</span> <span class="fu">length</span>(a)</span>
<span id="cb9-416"><a href="#cb9-416" aria-hidden="true" tabindex="-1"></a>  se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(ah <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> ah) <span class="sc">/</span> k <span class="sc">+</span> bh <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> bh) <span class="sc">/</span> k)</span>
<span id="cb9-417"><a href="#cb9-417" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (se <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">return</span>(<span class="dv">1</span>)</span>
<span id="cb9-418"><a href="#cb9-418" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> (ah <span class="sc">-</span> bh) <span class="sc">/</span> se</span>
<span id="cb9-419"><a href="#cb9-419" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z)))</span>
<span id="cb9-420"><a href="#cb9-420" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-421"><a href="#cb9-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-422"><a href="#cb9-422" aria-hidden="true" tabindex="-1"></a>any_significant <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_experiments, {</span>
<span id="cb9-423"><a href="#cb9-423" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">1</span>, pi_null)</span>
<span id="cb9-424"><a href="#cb9-424" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">1</span>, pi_null)</span>
<span id="cb9-425"><a href="#cb9-425" aria-hidden="true" tabindex="-1"></a>  p_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(peek_points, <span class="cf">function</span>(k) {</span>
<span id="cb9-426"><a href="#cb9-426" aria-hidden="true" tabindex="-1"></a>    <span class="fu">z_test_pvalue</span>(a[<span class="dv">1</span><span class="sc">:</span>k], b[<span class="dv">1</span><span class="sc">:</span>k])</span>
<span id="cb9-427"><a href="#cb9-427" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb9-428"><a href="#cb9-428" aria-hidden="true" tabindex="-1"></a>  <span class="fu">any</span>(p_values <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb9-429"><a href="#cb9-429" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-430"><a href="#cb9-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-431"><a href="#cb9-431" aria-hidden="true" tabindex="-1"></a>fpr_peeking <span class="ot">&lt;-</span> <span class="fu">mean</span>(any_significant)</span>
<span id="cb9-432"><a href="#cb9-432" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-433"><a href="#cb9-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-434"><a href="#cb9-434" aria-hidden="true" tabindex="-1"></a><span class="in">```{r peeking-table}</span></span>
<span id="cb9-435"><a href="#cb9-435" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-436"><a href="#cb9-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-437"><a href="#cb9-437" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb9-438"><a href="#cb9-438" aria-hidden="true" tabindex="-1"></a>  <span class="at">Quantity =</span> <span class="fu">c</span>(</span>
<span id="cb9-439"><a href="#cb9-439" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Nominal false positive rate (single test)"</span>,</span>
<span id="cb9-440"><a href="#cb9-440" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Empirical false positive rate (with peeking, 10 looks)"</span>,</span>
<span id="cb9-441"><a href="#cb9-441" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Inflation factor"</span></span>
<span id="cb9-442"><a href="#cb9-442" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb9-443"><a href="#cb9-443" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb9-444"><a href="#cb9-444" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>,  <span class="fl">0.05</span>),</span>
<span id="cb9-445"><a href="#cb9-445" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>,  fpr_peeking),</span>
<span id="cb9-446"><a href="#cb9-446" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%.2fx"</span>, fpr_peeking <span class="sc">/</span> <span class="fl">0.05</span>)</span>
<span id="cb9-447"><a href="#cb9-447" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-448"><a href="#cb9-448" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb9-449"><a href="#cb9-449" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">|&gt;</span></span>
<span id="cb9-450"><a href="#cb9-450" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_align</span>(<span class="at">align =</span> <span class="st">"right"</span>, <span class="at">columns =</span> Value) <span class="sc">|&gt;</span></span>
<span id="cb9-451"><a href="#cb9-451" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(</span>
<span id="cb9-452"><a href="#cb9-452" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">md</span>(<span class="st">"**False Positive Rate Under Repeated Peeking**"</span>),</span>
<span id="cb9-453"><a href="#cb9-453" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"10,000 simulated experiments under H₀: π_A = π_B = 0.20"</span></span>
<span id="cb9-454"><a href="#cb9-454" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb9-455"><a href="#cb9-455" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb9-456"><a href="#cb9-456" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.border.top.style =</span> <span class="st">"none"</span>,</span>
<span id="cb9-457"><a href="#cb9-457" aria-hidden="true" tabindex="-1"></a>    <span class="at">heading.align =</span> <span class="st">"left"</span></span>
<span id="cb9-458"><a href="#cb9-458" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-459"><a href="#cb9-459" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-460"><a href="#cb9-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-461"><a href="#cb9-461" aria-hidden="true" tabindex="-1"></a>The nominal false positive rate of a single test at $\alpha = 0.05$ is, by construction, 5%. Under the peeking procedure described above, it rises to roughly <span class="in">`r sprintf("%.0f%%", 100 * fpr_peeking)`</span> — between three and four times higher. Put plainly: an experimenter who peeks ten times, and stops the moment anything crosses the significance line, will falsely claim a winner about one time in five when in truth the two CTAs perform identically. The guarantees that the $p &lt; 0.05$ threshold was meant to provide have been quietly discarded.</span>
<span id="cb9-462"><a href="#cb9-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-463"><a href="#cb9-463" aria-hidden="true" tabindex="-1"></a>This is not a subtle technical quibble. It is the reason serious experimentation platforms — the ones operated by large technology companies — either fix the sample size in advance and resist the urge to stop early, or switch to procedures specifically designed to preserve the false positive rate under sequential monitoring (group sequential designs, always-valid p-values, Bayesian stopping rules). Classical frequentist hypothesis testing is not robust to being run repeatedly on accumulating data, and treating it as though it were is one of the most common and most consequential mistakes in applied A/B testing.</span>
<span id="cb9-464"><a href="#cb9-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-465"><a href="#cb9-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-466"><a href="#cb9-466" aria-hidden="true" tabindex="-1"></a><span class="fu">## Closing Remarks</span></span>
<span id="cb9-467"><a href="#cb9-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-468"><a href="#cb9-468" aria-hidden="true" tabindex="-1"></a>Taken together, the simulations above retrace the logic of classical frequentist inference on a single running example. The Law of Large Numbers assures us that the difference in sample means gets to the right answer given enough data. The Central Limit Theorem tells us the shape of its sampling distribution along the way, which lets us attach a standard error and build a confidence interval. The bootstrap supplies that standard error by resampling, and for this problem agrees closely with the analytical formula. Hypothesis testing converts the standardised estimate into a p-value that grades the evidence against a null of no effect. The regression framework reproduces the same inference in a form that generalises cleanly to richer designs. And the peeking simulation makes concrete how fragile the machinery becomes when its rules are bent — a reminder that frequentist guarantees hold only under the experimental protocol they assume.</span>
<span id="cb9-469"><a href="#cb9-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-470"><a href="#cb9-470" aria-hidden="true" tabindex="-1"></a>None of this is new; all of it is used, every day, to decide which copy, which layout, or which price a website should show its visitors. Simulating it end-to-end, with a known ground truth, is a useful exercise in appreciating both what these tools deliver and what they quietly require in return.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Guanzong (Alex) Zhong</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rsm-a4zhong">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/guanzong-zhong-58a4643a8/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:a4zhong@ucsd.edu">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>